stages:
  # - test
  - deploy

# test:
#   stage: test
#   only:
#     - master
#   script:
#     - ls
#     - cp src/* /home/gitlab-runner/CoronaNotify/test/
#     - cd /home/gitlab-runner/CoronaNotify/test
#     - ls
#     - python3 FetchBot2.py --test
#     - ls
#   tags:
#     - deploy

deploy-to-server:
  stage: deploy
  only:
    - master
  script:
    - ls
    - cp src/* /home/gitlab-runner/CoronaNotify/src/
    - cd /home/gitlab-runner/CoronaNotify/src
    - ls
  tags:
    - deploy